spring:
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:postgresql://localhost/postgres
#    username: postgres
#    password: secretadmin
#    initialization-mode: always
#    platform: postgres





